### ISSUE TITLE
提交和修改打印任务时报错，unknown column 'double'

### ISSUE THREAD

**Issue by crisone** [YunYinORG/YunYinService#9]
提交时报错
<br />
<b>Fatal error</b>:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'double' in 'field list'' in /var/www/html/app/library/Service/Db.php:63
Stack trace:
#0 /var/www/html/app/library/Service/Db.php(63): PDO-&gt;prepare('INSERT INTO`tas...')
#1 /var/www/html/app/library/Service/Db.php(152): Service\Db-&gt;init('INSERT INTO`tas...', Array)
#2 /var/www/html/app/library/Model.php(359): Service\Db-&gt;execute('INSERT INTO`tas...', Array)
#3 /var/www/html/app/library/Model.php(266): Model-&gt;execute('INSERT INTO`tas...', Array)
#4 [internal function]: Model-&gt;insert(Array)
#5 /var/www/html/app/models/Facade.php(130): call_user_func_array(Array, Array)
#6 /var/www/html/app/controllers/Task.php(58): FacadeModel::__callStatic('insert', Array)
#7 /var/www/html/app/controllers/Task.php(58): TaskModel::insert(Array)
#8 [internal function]: TaskController-&gt;POST_indexAction()
#9 /var/www/html/index.php(4): Yaf_Application-&gt;run()
#10 {main}
  thrown in <b>/var/www/html/app/library/Service/Db.php</b> on line <b>63</b><br />

修改时报错
<br />
<b>Fatal error</b>:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'double' in 'field list'' in /var/www/html/app/library/Service/Db.php:63
Stack trace:
#0 /var/www/html/app/library/Service/Db.php(63): PDO-&gt;prepare('UPDATE`task`SET...')
#1 /var/www/html/app/library/Service/Db.php(152): Service\Db-&gt;init('UPDATE`task`SET...', Array)
#2 /var/www/html/app/library/Model.php(359): Service\Db-&gt;execute('UPDATE`task`SET...', Array)
#3 /var/www/html/app/library/Model.php(217): Model-&gt;execute('UPDATE`task`SET...', Array)
#4 /var/www/html/app/controllers/Task.php(104): Model-&gt;update(Array)
#5 [internal function]: TaskController-&gt;PUT_infoAction(2)
#6 /var/www/html/index.php(4): Yaf_Application-&gt;run()
#7 {main}
  thrown in <b>/var/www/html/app/library/Service/Db.php</b> on line <b>63</b><br />

**Comment by crisone** [comment]
数据库是最新的，是不是 isdouble 写成 double 了
